### ISSUE TITLE
CMake does not check that msgpack is installed

### ISSUE THREAD

**Issue by akien-mga** [freeminer/freeminer#181]
Everything is in the title, there should be a FindMsgPack.cmake module checking for the availability of the msgpack headers and libraries on the user's system.

For Linux systems, adapting this CMake example would be enough, but I don't know for Windows and Mac.

**Comment by crazyginger72** [comment]
I don't know but this may be linked to #185

**Comment by proller** [comment]
https://github.com/freeminer/freeminer/commit/072d3b2b5b402fa2d4b3e4ea6118f28d7d1e5cd9
