### ISSUE TITLE
msgpack.hpp not found ERROR

### ISSUE THREAD

**Issue by crazyginger72** [freeminer/freeminer#185]
/home/cg72/freeminer/src/msgpack.h:6:10: fatal error: 'msgpack.hpp' file not found
#include <msgpack.hpp>

ok did you mean .cpp?  either way there is no file under that name in the src dir.

**Comment by akien-mga** [comment]
It is linked with #181 indeed. You need to install msgpack on your system in a path that the current CMake script can locate (probably in /usr/lib and /usr/include, unless you add /usr/local/lib and /usr/local/include to the linking and include paths).

**Comment by akien-mga** [comment]
Msgpack can be found here: http://msgpack.org/

**Comment by crazyginger72** [comment]
thank you alot :) i will get right on it

**Comment by proller** [comment]
not found error added.

**Comment by ax-el** [comment]
In ubuntu 18.10 msgpack.hpp is provided in libmsgpack-dev ==>
sudo apt install libmsgpack-dev
