### ISSUE TITLE
Error with msgpack 1.0.0

### ISSUE THREAD

**Issue by AlfredoRamos** [freeminer/freeminer#197]
Hi there,

Today ```msgpack-c``` package was moved to the community official repositories (see #196). It now provides the version [1.0.0](https://github.com/msgpack/msgpack-c/releases) (released ~6 hours ago) and for now i couldn't compile it.

I think it's a msgpack problem, i've been using msgpack 0.5.* previously with no problems.

The full output: https://pastebin.osuosl.org/16231/

So the question is, have someone been able to compile freeminer with msgpack 1.0.0?

I maintain both packages in the AUR, so if i can't get it work with the latest version, i'll try using an old one.

**Comment by proller** [comment]
its real issue and should be fixed

**Comment by donat-b** [comment]
hm, didn't realize it would close this issue as well

**Comment by proller** [comment]
fixed for msgpack 1.1.0 
https://github.com/freeminer/freeminer/commit/9a1726a0477a04efd51c42629546fe4865e1c8e3

**Comment by AlfredoRamos** [comment]
I think this is fixed then, since msgpack 1.1.0 is now the only version available in Arch.
