### ISSUE TITLE
[Android] Tapping outside the chat box causes damage

### ISSUE THREAD

**Issue by Wayward1** [freeminer/freeminer#221]
While playing on the latest Feeminer build, I noticed that if you open the chat box and touch outside the keyboard and text box (below), the player loses about half their health. I've only noticed this once each time the chat box is opened.

I have no extra mods installed.

Note the two deaths, caused by opening the chat box, tapping an empty part of the screen, closing it, and repeating three more times.
![screenshot_2015-08-28-13-38-42](https://cloud.githubusercontent.com/assets/8821916/9553158/30eb81de-4d8b-11e5-8fac-3075c4db2a69.png)

**Comment by proller** [comment]
broken here e823f357a068a0ef08f0300c6384592ec321dd91 

-       m_move_max_loop(10)
+       m_move_max_loop(3)

-       if (!breaked && m_move_max_loop < 50)
+       if (!breaked && m_move_max_loop < 5)

something strange with collision detect

**Comment by proller** [comment]
d25170c159462a3cee497328e1b542e22d9af292

fixed ?
