### ISSUE TITLE
shadows don't work

### ISSUE THREAD

**Issue by HybridDog** [freeminer/freeminer#240]
![screenshot_20151007_190025](https://cloud.githubusercontent.com/assets/3192173/10344862/f9d1e570-6d25-11e5-9f70-e3a59c11719d.png)

shadows are enabled but don't work, it should look like that l think:
![shait](https://cloud.githubusercontent.com/assets/3192173/10344900/30a53c1e-6d26-11e5-8616-e159fb7307ef.png)

**Comment by proller** [comment]
lost in another merge of mt refucktoring
671c571e8249152600281fc3153d5873528fa0c8
but shadows still too ugly.
note: irrlicht 1.8.2+ needed

**Comment by HybridDog** [comment]
thanks, in my opinion they don't look ugly
