### ISSUE TITLE
beginning to type a command but aborting doesn't remove the "/"

### ISSUE THREAD

**Issue by HybridDog** [freeminer/freeminer#241]
When l press b to type a command, it opens the chat overlay and writes a /. If l then press Esc, continue and press t for usual chat, it is still there.

**Comment by donat-b** [comment]
I'll try to find time to look into that.

**Comment by donat-b** [comment]
Looks like there are two options:
- clearing input when opening chat completely
- removing just the slash if it's present.
First one isn't a perfect solution as it's not always handy to lose your input if you just wanted to switch for a second.
Opinions?

**Comment by HybridDog** [comment]
l prefer the second one.

**Comment by alexxvk** [comment]
Possible third option: 
* clearing input when opening chat completely but save uncompleted text in chat history

I think this solution is better than the first two options.

**Comment by HybridDog** [comment]
does chat history mean that you press the ↑ arrow and the messages you wrote before reappear?

**Comment by donat-b** [comment]
@HybridDog correct
