### ISSUE TITLE
Readme.md: suggest using apt-fast instead of apt-get

### ISSUE THREAD

**Issue by HybridDog** [freeminer/freeminer#254]
https://github.com/ilikenwf/apt-fast
l found that ↑

**Comment by donat-b** [comment]
Seems kinda awkward mentioning it since it's not in the official repos.
I think much more time is spent reading database and installing packages than downloading them.

**Comment by HybridDog** [comment]
l recently got a bad connection for any reason, ca. 200 kB/s, so it was/is very useful to me.
