### ISSUE TITLE
Wrong source tarball for 0.4.13.7

### ISSUE THREAD

**Issue by Khyota** [freeminer/freeminer#261]
The release tarball for 0.4.13.7 contains freeminer-default and not the engine source code. https://github.com/freeminer/freeminer/archive/0.4.13.7.tar.gz

**Comment by donat-b** [comment]
Just downloaded the tarball and it does contain the engine source code...
Although it doesn't contain the submodules which is a problem.

**Comment by proller** [comment]
this is automatic github archive without submodules.

better use this, manually packed: https://github.com/freeminer/freeminer/releases/download/0.4.13.7/freeminer-0.4.13.7.zip

**Comment by Khyota** [comment]
That was really odd. Perhaps I was just a locally cached version since freeminer-default used the same filename. Including submodules will make packaging a lot easier.
