### ISSUE TITLE
Android：Virtual Controls

### ISSUE THREAD

**Issue by Pantyhose-X** [freeminer/freeminer#294]
## Problem
Add virtual controls for easier operation

## Solutions
Custom Controls https://www.youtube.com/watch?v=pNUYuymoiuA
![image](https://user-images.githubusercontent.com/42504385/219325283-dc8f31d8-128c-41e5-b3e2-3ba851493efa.png)

![](https://preview.redd.it/xcxqwm4q2js81.jpg?width=2400&format=pjpg&auto=webp&v=enabled&s=64572b06b83c47e2609d7e549417b648bc8261df)

**Comment by mckaygerhard** [comment]
@proller  your project is based on minetest.. so its so obvious that androit controls are a crap.. i suggest to check some of the changes of multicraft and also other project.. not only multicraft.. 

@Pantyhose-X  you should take into account that making this need so much work and there's little collaboration..

**Comment by mckaygerhard** [comment]
also 5.6 servers are not so used.. sorry

**Comment by Pantyhose-X** [comment]
freeminer offers a Roadmap for future development, in order to attract more number of contributors.
