### ISSUE TITLE
Clay is not an ore to be mined

### ISSUE THREAD

**Issue by Philipbenr** [freeminer/freeminer#83]
I know this from experience... Clay is not an ore to be mined, and it is just like wet sand except for it is thicker (and it has other uses yes, but I am talking about texture/consistency). The grid is rather annoying as well, so I am suggesting that we change it. I also have a texture if you wish to keep it close to what it is like now. This is in a rather old post too: http://forum.freeminer.org/threads/feature-discussion.70/page-2#post-802 Texture is WTFPL.

I don't know if this was already reviewed by proller or xyz or another contributor, and if it was, please tell me. If I am asking the wrong thing, please tell me before shutting it down or, just ask me to please shut-up... Sorry for being a pill.

**Comment by donat-b** [comment]
I guess it's good to be closed now.
